using System;

namespace UglyTrivia
{
    public class GoldenMasterData
    {
        public static String[] data = 
        {
            "\n\n--- Trivia Game ---\nChet was added\nThey are player number 1\nPat was added\nThey are player number 2\nSue was added\nThey are player number 3\nChet is the current player\nThey have rolled a 2\nChet's new location is 2\nThe category is Sports\nSports Question 0\nAnswer was corrent!!!!\nChet now has 1 Gold Coins.\nPat is the current player\nThey have rolled a 5\nPat's new location is 5\nThe category is Science\nScience Question 0\nAnswer was corrent!!!!\nPat now has 1 Gold Coins.\nSue is the current player\nThey have rolled a 4\nSue's new location is 4\nThe category is Pop\nPop Question 0\nAnswer was corrent!!!!\nSue now has 1 Gold Coins.\nChet is the current player\nThey have rolled a 5\nChet's new location is 7\nThe category is Rock\nRock Question 0\nAnswer was corrent!!!!\nChet now has 2 Gold Coins.\nPat is the current player\nThey have rolled a 2\nPat's new location is 7\nThe category is Rock\nRock Question 1\nAnswer was corrent!!!!\nPat now has 2 Gold Coins.\nSue is the current player\nThey have rolled a 3\nSue's new location is 7\nThe category is Rock\nRock Question 2\nQuestion was incorrectly answered\nSue was sent to the penalty box\nChet is the current player\nThey have rolled a 4\nChet's new location is 11\nThe category is Rock\nRock Question 3\nAnswer was corrent!!!!\nChet now has 3 Gold Coins.\nPat is the current player\nThey have rolled a 1\nPat's new location is 8\nThe category is Pop\nPop Question 1\nAnswer was corrent!!!!\nPat now has 3 Gold Coins.\nSue is the current player\nThey have rolled a 2\nSue is not getting out of the penalty box\nChet is the current player\nThey have rolled a 2\nChet's new location is 1\nThe category is Science\nScience Question 1\nAnswer was corrent!!!!\nChet now has 4 Gold Coins.\nPat is the current player\nThey have rolled a 4\nPat's new location is 0\nThe category is Pop\nPop Question 2\nAnswer was corrent!!!!\nPat now has 4 Gold Coins.\nSue is the current player\nThey have rolled a 4\nSue is not getting out of the penalty box\nChet is the current player\nThey have rolled a 3\nChet's new location is 4\nThe category is Pop\nPop Question 3\nAnswer was corrent!!!!\nChet now has 5 Gold Coins.\nPat is the current player\nThey have rolled a 2\nPat's new location is 2\nThe category is Sports\nSports Question 1\nAnswer was corrent!!!!\nPat now has 5 Gold Coins.\nSue is the current player\nThey have rolled a 3\nSue is getting out of the penalty box\nSue's new location is 10\nThe category is Sports\nSports Question 2\nAnswer was correct!!!!\nSue now has 2 Gold Coins.\nChet is the current player\nThey have rolled a 4\nChet's new location is 8\nThe category is Pop\nPop Question 4\nAnswer was corrent!!!!\nChet now has 6 Gold Coins.\n",
            "\n\n--- Trivia Game ---\nChet was added\nThey are player number 1\nPat was added\nThey are player number 2\nSue was added\nThey are player number 3\nChet is the current player\nThey have rolled a 1\nChet's new location is 1\nThe category is Science\nScience Question 0\nAnswer was corrent!!!!\nChet now has 1 Gold Coins.\nPat is the current player\nThey have rolled a 5\nPat's new location is 5\nThe category is Science\nScience Question 1\nAnswer was corrent!!!!\nPat now has 1 Gold Coins.\nSue is the current player\nThey have rolled a 3\nSue's new location is 3\nThe category is Rock\nRock Question 0\nAnswer was corrent!!!!\nSue now has 1 Gold Coins.\nChet is the current player\nThey have rolled a 5\nChet's new location is 6\nThe category is Sports\nSports Question 0\nAnswer was corrent!!!!\nChet now has 2 Gold Coins.\nPat is the current player\nThey have rolled a 2\nPat's new location is 7\nThe category is Rock\nRock Question 1\nAnswer was corrent!!!!\nPat now has 2 Gold Coins.\nSue is the current player\nThey have rolled a 2\nSue's new location is 5\nThe category is Science\nScience Question 2\nQuestion was incorrectly answered\nSue was sent to the penalty box\nChet is the current player\nThey have rolled a 4\nChet's new location is 10\nThe category is Sports\nSports Question 1\nAnswer was corrent!!!!\nChet now has 3 Gold Coins.\nPat is the current player\nThey have rolled a 1\nPat's new location is 8\nThe category is Pop\nPop Question 0\nAnswer was corrent!!!!\nPat now has 3 Gold Coins.\nSue is the current player\nThey have rolled a 3\nSue is getting out of the penalty box\nSue's new location is 8\nThe category is Pop\nPop Question 1\nQuestion was incorrectly answered\nSue was sent to the penalty box\nChet is the current player\nThey have rolled a 5\nChet's new location is 3\nThe category is Rock\nRock Question 2\nAnswer was corrent!!!!\nChet now has 4 Gold Coins.\nPat is the current player\nThey have rolled a 4\nPat's new location is 0\nThe category is Pop\nPop Question 2\nAnswer was corrent!!!!\nPat now has 4 Gold Coins.\nSue is the current player\nThey have rolled a 4\nSue is not getting out of the penalty box\nChet is the current player\nThey have rolled a 2\nChet's new location is 5\nThe category is Science\nScience Question 3\nAnswer was corrent!!!!\nChet now has 5 Gold Coins.\nPat is the current player\nThey have rolled a 1\nPat's new location is 1\nThe category is Science\nScience Question 4\nAnswer was corrent!!!!\nPat now has 5 Gold Coins.\nSue is the current player\nThey have rolled a 4\nSue is not getting out of the penalty box\nChet is the current player\nThey have rolled a 4\nChet's new location is 9\nThe category is Science\nScience Question 5\nAnswer was corrent!!!!\nChet now has 6 Gold Coins.\n",            
            ""
        };
    }
}
